In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

In [5]:
driver = webdriver.Chrome(executable_path=r"C:\Users\Owner\Desktop\DS\chromedriver\chromedriver.exe")

In [82]:
name=[] #List to store name of the product
category=[]
description=[]
prices=[] #List to store price of the product
location=[] #List to store rating of the product

In [141]:
for i in range(200):
    driver.get("https://www.luxstay.com/s/?page={}".format(i+1))
    content = driver.page_source
    soup = BeautifulSoup(content)
    for a in soup.findAll('div', attrs={'class':'col-xs-6 col-md-3 col-lg-20'}):
        cat=a.find('div', attrs={'class':"promo__type bold"})
        des=a.find('div', attrs={'class':'promo__description my--6 text-lowercase'})
        tit=a.find('div', attrs={'class':'promo__title extra-bold'})
        pri=a.find('div', attrs={'class':'promo__price mb--6'})
        loc=a.find('div', attrs={'class':'promo__add mb--6 promo__add mb--6'})
        if cat == None:
            category.append('Invalid')
        else:
            category.append(cat.text)
        if tit == None:
            name.append('Invalid')
        else:
            name.append(tit.text)
        if des == None:
            description.append('Invalid')
        else:
            description.append(des.text)
        if pri == None:
            prices.append('Invalid')
        else:
            prices.append(pri.text)
        if loc == None:
            location.append('Invalid')
        else:
            location.append(loc.text)

In [151]:
import re
name_temp = []
for i in range(len(name)):
    if name[i] != 'Invalid':
        try:
            name_temp.append(re.split(r'\n            |\n          ',name[i])[1])
        except:
            print(i)
            break
    else:
        name_temp.append(name[i])
df1 = pd.DataFrame(name_temp,columns = ['name'])
print(df1)

                                                   name
0                             San's Home [Sharing home]
1                                         Chillin House
2     MLibrary Pentstudio Apartment West Lake with P...
3       Win Aparment Studio Tiêu chuẩn (Min 2 night) #1
4     ✦Luxury Villa 6BR✦Thao Dien Dist 2✦Bathtub✦Big...
...                                                 ...
3255                                            Invalid
3256                                            Invalid
3257                                            Invalid
3258                                            Invalid
3259                                            Invalid

[3260 rows x 1 columns]

In [152]:
cat_temp = []
for i in range(len(category)):
    if category[i] != 'Invalid':
        temp = re.split(r'\n        |\n         | ·  ',category[i])
        if len(temp)<2:
            cat_temp.append(('None','None'))
        elif len(temp)<4:
            cat_temp.append((temp[1],'None'))
        else:
            cat_temp.append((temp[1],temp[3]))
    else:
        cat_temp.append(('None','None'))
df2 = pd.DataFrame(cat_temp, columns = ['category','project'])
print(df2)

               category          project
0           Condominium    Nam Trung Yên
1     Service Apartment  Vũng Tàu Melody
2                  None             None
3      Studio Apartment             None
4                 Villa             None
...                 ...              ...
3255               None             None
3256               None             None
3257               None             None
3258               None             None
3259               None             None

[3260 rows x 2 columns]

In [153]:
des_temp = []
for i in range(len(description)):
    if description[i] != 'Invalid':
        temp = re.split(r' guests · | guest · | Bedroom · | Bedrooms · | Bedrooms| Bedroom| bathrooms| bathroom',description[i])[0:3]
        temp = tuple([x if x else '0' for x in temp])
        des_temp.append(temp)
    else:
        des_temp.append(('0','0','0'))
df3 = pd.DataFrame(des_temp, columns = ['guest','bedroom','bathroom'])
print(df3)

     guest bedroom bathroom
0        2       1        1
1       12       3        2
2        6       1        1
3        3       1        1
4       16       6        8
...    ...     ...      ...
3255     0       0        0
3256     0       0        0
3257     0       0        0
3258     0       0        0
3259     0       0        0

[3260 rows x 3 columns]

In [154]:
pri_temp = []
for i in range(len(prices)):
    if prices[i] != 'Invalid':
        temp = re.split(r'/night \$|/night | \$',prices[i])
        if temp[2]:
            pri_temp.append((temp[1],'1',temp[2]))
        else:
            pri_temp.append((temp[1],'0','Invalid'))
    else:
        pri_temp.append(('0','0','Invalid'))
df4 = pd.DataFrame(pri_temp, columns = ['price','discounted','normal price'])
print(df4)

     price discounted normal price
0       13          0      Invalid
1       47          1           58
2       74          0      Invalid
3       11          0      Invalid
4      275          1          305
...    ...        ...          ...
3255     0          0      Invalid
3256     0          0      Invalid
3257     0          0      Invalid
3258     0          0      Invalid
3259     0          0      Invalid

[3260 rows x 3 columns]

In [155]:
loc_temp = [tuple(re.split(r', ',location[i])) if location[i] != 'Invalid' else ('Invalid','Invalid','Invalid') for i in range(len(location))]
df5 = pd.DataFrame(loc_temp, columns = ['province','state','country'])
print(df5)

      province            state  country
0     Cầu Giấy           Hà Nội  Vietnam
1     Vũng Tàu  Bà Rịa Vũng Tàu  Vietnam
2       Tây Hồ           Hà Nội  Vietnam
3      Sơn Trà          Đà Nẵng  Vietnam
4       Quận 2      Hồ Chí Minh  Vietnam
...        ...              ...      ...
3255   Invalid          Invalid  Invalid
3256   Invalid          Invalid  Invalid
3257   Invalid          Invalid  Invalid
3258   Invalid          Invalid  Invalid
3259   Invalid          Invalid  Invalid

[3260 rows x 3 columns]

In [156]:
print(len(name_temp),len(cat_temp),len(des_temp),len(pri_temp),len(loc_temp))

3260 3260 3260 3260 3260

In [157]:
df = pd.concat([df1,df2,df3,df4,df5],axis = 1)
df.to_csv("./result200.csv",encoding='utf-8-sig')
df

,name,category,project,guest,bedroom,bathroom,price,discounted,normal price,province,state,country
0,San's Home [Sharing home],Condominium,Nam Trung Yên,2,1,1,13,0,Invalid,Cầu Giấy,Hà Nội,Vietnam
1,Chillin House,Service Apartment,Vũng Tàu Melody,12,3,2,47,1,58,Vũng Tàu,Bà Rịa Vũng Tàu,Vietnam
2,MLibrary Pentstudio Apartment West Lake with P...,None,None,6,1,1,74,0,Invalid,Tây Hồ,Hà Nội,Vietnam
3,Win Aparment Studio Tiêu chuẩn (Min 2 night) #1,Studio Apartment,None,3,1,1,11,0,Invalid,Sơn Trà,Đà Nẵng,Vietnam
4,✦Luxury Villa 6BR✦Thao Dien Dist 2✦Bathtub✦Big...,Villa,None,16,6,8,275,1,305,Quận 2,Hồ Chí Minh,Vietnam
...,...,...,...,...,...,...,...,...,...,...,...,...
3255,Invalid,None,None,0,0,0,0,0,Invalid,Invalid,Invalid,Invalid
3256,Invalid,None,None,0,0,0,0,0,Invalid,Invalid,Invalid,Invalid
3257,Invalid,None,None,0,0,0,0,0,Invalid,Invalid,Invalid,Invalid
3258,Invalid,None,None,0,0,0,0,0,Invalid,Invalid,Invalid,Invalid
3259,Invalid,None,None,0,0,0,0,0,Invalid,Invalid,Invalid,Invalid